import torch
import numpy as np

from train_mnist import HardwareCNN

# Load in the weights and the model

weights_path = "../mnist_hw_model.pth"

model = HardwareCNN()
model.load_state_dict(torch.load(weights_path))
weights = model.conv1.weight.data.numpy()

# for debugging
print("Raw weights")
print(weights)


def convert_to_a312(val):
    # quite simple, left shift 12 bits. i.e multiply by 2^12 (4096)

    # has a range of -8.000000 to 7.999755

    val = int(round(val*4096)) # clip to the nearest bit in precision

    # clamp at limits of -2^15, 2^15 - 1
    val = max(-(2**15), min((2**15 - 1), val))

    # convert 
    if val < 0:
        val = 2**16 + val
    return f"{val:04X}" # returns something like 01F9

if __name__ == "__main__":

    print("Converting weights... Paste in to verilog file: \n")
    print("// generated by weights_extraction.py, in A3.12 format |S|III|FFFFFFFFFFFF|")
    i = 0
    # note that we have to first convert the weights into a useable format
    for weight in weights:
        weight = weight[0].flatten()
        weight = weight[::-1]
        hex_vals = [convert_to_a312(weigh) for weigh in weight]
        hex_vals = "".join(hex_vals)

        print(f"assign weight_lane[{i}] = 144'h{hex_vals};")
        i += 1